# Generated by Django 6.1 on 2026-08-27 18:12

import django.db.models.deletion
import feed.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_assignment_unarchived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Імʼя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('file', models.FileField(blank=True, null=True, upload_to=feed.models.submission_upload_path, verbose_name='Файл роботи')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання на роботу')),
                ('comment_student', models.TextField(blank=True, help_text="Необов'язковий коментар до здачі", null=True, verbose_name='Коментар учня')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Час здачі')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Оцінка')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name='Коментар вчителя')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Час оцінювання')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='feed.assignment', verbose_name='Завдання')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.classgroup', verbose_name='Клас')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Оцінив (вчитель)')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_submissions', to='feed.teacher', verbose_name='Вчитель (кому здано)')),
            ],
            options={
                'verbose_name': 'Здача роботи',
                'verbose_name_plural': 'Здачі робіт',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submission', 'Здача роботи'), ('grading', 'Оцінювання'), ('comment', 'Коментар')], max_length=20, verbose_name='Тип дії')),
                ('description', models.TextField(verbose_name='Опис')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='feed.submission', verbose_name='Здача')),
            ],
            options={
                'verbose_name': 'Журнал дій',
                'verbose_name_plural': 'Журнал дій',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст коментаря')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.submission', verbose_name='Здача')),
            ],
            options={
                'verbose_name': 'Коментар до здачі',
                'verbose_name_plural': 'Коментарі до здач',
                'ordering': ['created_at'],
            },
        ),
    ]
