# Generated by Django 6.1 on 2026-08-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_submission_submissionactivitylog_submissioncomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionactivitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Вхід в систему'), ('submission', 'Здача роботи'), ('grading', 'Оцінювання'), ('comment', 'Коментар'), ('delete', 'Видалення')], max_length=20, verbose_name='Тип дії'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Наш Заклад Освіти', max_length=200, verbose_name='Назва школи / закладу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to=settings.AUTH_USER_MODEL, verbose_name='Головний адміністратор')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школа',
            },
        ),
    ]
