# Generated by Django 6.1 on 2026-08-27 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_alter_submissionactivitylog_action_type_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['class_group', 'submitted_at'], name='feed_submis_class_g_dd9bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['last_name', 'first_name'], name='feed_submis_last_na_aff213_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['grade'], name='feed_submis_grade_ac0973_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'class_group'], name='feed_submis_assignm_9bfe19_idx'),
        ),
    ]
