# Generated by Django 6.1 on 2026-08-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_submission_feed_submis_class_g_dd9bb5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', help_text='Отримайте безкоштовний ключ в Google AI Studio', max_length=255, verbose_name='Google Gemini API Key')),
                ('model_name', models.CharField(default='gemini-2.0-flash', help_text='Наприклад: gemini-2.0-flash, gemini-1.5-flash, gemini-1.5-pro', max_length=100, verbose_name='Модель Gemini')),
                ('system_prompt', models.TextField(default='Ти — висококваліфікований шкільний педагог-експерт з оцінювання за критеріями Нової української школи (НУШ).\nТвоє завдання — об\'єктивно, доброзичливо та конструктивно проаналізувати виконане учнем завдання у порівнянні з умовою, вимогами вчителя та матеріалами уроку.\n\nКРИТЕРІЇ ТА ШКАЛА ОЦІНЮВАННЯ НУШ (1-12 БАЛІВ):\n1. Початковий рівень (1-3 бали):\n   - 1-3 бали: учень володіє лише фрагментарними знаннями, завдання виконано частково з грубими помилками або тема розкрита поверхнево.\n2. Середній рівень (4-6 балів):\n   - 4-6 балів: учень відтворює основний навчальний матеріал за зразком, присутні типові неточності чи розрахункові помилки, але базову структуру збережено.\n3. Достатній рівень (7-9 балів):\n   - 7-9 балів: учень самостійно застосовує знання у стандартних ситуаціях, правильно розв\'язано більшість завдань, робота містить незначні неточності чи погрішності в оформленні.\n4. Високий рівень (10-12 балів):\n   - 10-12 балів: глибоке засвоєння теми, бездоганне виконання, логічність, творчий підхід, обґрунтованість висновків та охайність.\n\nОСОБЛИВИЙ СТАТУС "Доопрацювати":\nЯкщо робота не відповідає темі завдання, здано порожній файл, або допущено критичні помилки, які вимагають переробки учнем, вкажи рекомендовану оцінку "Доопрацювати".\n\nФОРМАТ ВІДПОВІДІ (ТІЛЬКИ ВАЛІДНИЙ JSON БЕЗ ЗАЙВОГО ТЕКСТУ):\n{\n  "suggested_grade": "11",\n  "level": "Високий (10-12)",\n  "summary": "Короткий загальний висновок щодо якості виконання.",\n  "strengths": ["Пункт 1: що зроблено відмінно", "Пункт 2: сильна сторона"],\n  "weaknesses": ["Пункт 1: на що звернути увагу чи де допущено неточність"],\n  "feedback_comment": "Повний розгорнутий доброзичливий відгук вчителя для учня з порадами.",\n  "status": "success"\n}\n', verbose_name='Системний промт (Критерії НУШ)')),
                ('temperature', models.FloatField(default=0.2, verbose_name='Температура (креативність)')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Модуль ШІ увімкнено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
            ],
            options={
                'verbose_name': 'Налаштування ШІ (Gemini)',
                'verbose_name_plural': 'Налаштування ШІ (Gemini)',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_error_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина помилки або відхилення ШІ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.TextField(blank=True, default='', verbose_name='Педагогічний відгук ШІ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час перевірки ШІ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_score_level',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Рівень оцінки ШІ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_status',
            field=models.CharField(choices=[('none', 'Не перевірялось'), ('success', 'Перевірено ШІ'), ('failed', 'Помилка перевірки'), ('unsupported', 'Формат не підтримується')], default='none', max_length=20, verbose_name='Статус перевірки ШІ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_suggested_grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Попередня оцінка ШІ'),
        ),
    ]
