# Generated by Django 6.1 on 2026-08-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_aisettings_submission_ai_error_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='saved_models_list',
            field=models.TextField(blank=True, default='["gemini-2.5-flash", "gemini-1.5-flash", "gemini-2.5-pro", "gemini-3.6-flash"]', verbose_name='Збережені моделі'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_model_used',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Використана модель ШІ'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', help_text='Наприклад: gemini-2.5-flash, gemini-1.5-flash, gemini-2.5-pro', max_length=100, verbose_name='Модель Gemini'),
        ),
    ]
