# Generated by Django 6.1 on 2026-08-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_aisettings_saved_models_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICriteriaPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва шаблону')),
                ('description', models.TextField(blank=True, default='', verbose_name='Короткий опис')),
                ('evaluation_type', models.CharField(choices=[('nus', '🌟 Оцінювання за стандартами НУШ (Компетентнісне)'), ('traditional', '📊 Класична / Традиційна система оцінювання (1-12 балів)'), ('custom', '📝 Власні критерії / Методичні рекомендації МОН')], default='nus', max_length=30, verbose_name='Тип системи оцінювання')),
                ('system_prompt', models.TextField(blank=True, default='', verbose_name='Системний промт інструкції для ШІ')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='ai_criteria_docs/', verbose_name='Документ із критеріями МОН (.docx, .pdf, .txt)')),
                ('document_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва файлу')),
                ('extracted_criteria_text', models.TextField(blank=True, default='', verbose_name='Видобутий текст критеріїв із файлу')),
                ('is_default', models.BooleanField(default=False, verbose_name='Активний за замовчуванням')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системний базовий шаблон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Шаблон критеріїв оцінювання ШІ',
                'verbose_name_plural': 'Шаблони критеріїв оцінювання ШІ',
                'ordering': ['-is_default', '-is_system', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', help_text='Основна модель (Пріоритет #1)', max_length=100, verbose_name='Модель Gemini'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='saved_models_list',
            field=models.TextField(blank=True, default='[{"name": "gemini-2.5-flash", "priority": 1, "enabled": true}, {"name": "gemini-1.5-flash", "priority": 2, "enabled": true}, {"name": "gemini-2.5-pro", "priority": 3, "enabled": true}, {"name": "gemini-3.6-flash", "priority": 4, "enabled": true}]', verbose_name='Збережені моделі з пріоритетами'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='system_prompt',
            field=models.TextField(default='Ти — висококваліфікований шкільний педагог-експерт з оцінювання за критеріями Нової української школи (НУШ).\nТвоє завдання — об\'єктивно, доброзичливо та конструктивно проаналізувати виконане учнем завдання у порівнянні з умовою, вимогами вчителя та матеріалами уроку.\n\nКРИТЕРІЇ ТА ШКАЛА ОЦІНЮВАННЯ НУШ (1-12 БАЛІВ):\n1. Початковий рівень (1-3 бали):\n   - 1-3 бали: учень володіє лише фрагментарними знаннями, завдання виконано частково з грубими помилками або тема розкрита поверхнево.\n2. Середній рівень (4-6 балів):\n   - 4-6 балів: учень відтворює основний навчальний матеріал за зразком, присутні типові неточності чи розрахункові помилки, але базову структуру збережено.\n3. Достатній рівень (7-9 балів):\n   - 7-9 балів: учень самостійно застосовує знання у стандартних ситуаціях, правильно розв\'язано більшість завдань, робота містить незначні неточності чи погрішності в оформленні.\n4. Високий рівень (10-12 балів):\n   - 10-12 балів: глибоке засвоєння теми, бездоганне виконання, логічність, творчий підхід, обґрунтованість висновків та охайність.\n\nТЕХНІЧНІ ВИМОГИ ТА ВІДПОВІДНІСТЬ ФОРМАТУ ФАЙЛУ (ОБОВ\'ЯЗКОВО ВРАХОВУВАТИ):\n- Звертай сувору увагу на формат прикріпленого учнем файлу та його відповідність суті завдання:\n  1. Якщо завдання з програмування (наприклад, Python, JS, C++ тощо), код повинен бути збережений у файлі з належним розширенням (наприклад, .py для Python, .html для веб, .cpp для C++).\n  2. Якщо файл здано БЕЗ РОЗШИРЕННЯ (навіть якщо всередині правильний код чи текст), або здано у невідповідному форматі (наприклад, текстовий файл .txt замість .py коду чи замість .xlsx таблиці, або фото замість коду):\n     * Обов\'язково зафіксуй це у полі "format_warning" (наприклад: "Файл здано без розширення (має бути .py для коду Python)").\n     * Обов\'язково додай це зауваження до списку "weaknesses" та у "feedback_comment".\n     * ЗНИЗЬ рекомендовану оцінку на 1-2 бали за порушення технічних вимог до формату здачі, навіть якщо саме завдання виконано правильно за логікою!\n  3. Якщо формат файлу повністю відповідає вимогам завдання, поле "format_warning" має бути null (або порожнім).\n\nОСОБЛИВИЙ СТАТУС "Доопрацювати":\nЯкщо робота не відповідає темі завдання, здано порожній файл, або допущено критичні помилки, які вимагають переробки учнем, вкажи рекомендовану оцінку "Доопрацювати".\n\nФОРМАТ ВІДПОВІДІ (ТІЛЬКИ ВАЛІДНИЙ JSON БЕЗ ЗАЙВОГО ТЕКСТУ):\n{\n  "suggested_grade": "10",\n  "level": "Високий (10-12)",\n  "format_warning": "Файл прикріплено без розширення (для коду Python очікується файл .py). Знижено 1 бал за оформлення.",\n  "summary": "Короткий загальний висновок щодо якості виконання та формату.",\n  "strengths": ["Пункт 1: що зроблено відмінно", "Пункт 2: сильна сторона"],\n  "weaknesses": ["Пункт 1: на що звернути увагу, помилки або невідповідність формату файлу"],\n  "feedback_comment": "Повний розгорнутий доброзичливий відгук вчителя для учня з порадами (включаючи зауваження щодо формату файлу, якщо воно є).",\n  "status": "success"\n}\n', verbose_name='Системний промт (Критерії НУШ)'),
        ),
    ]
