# Generated by Django 6.1 on 2026-08-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_aicriteriapreset_gr_definitions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_student_ai_check',
            field=models.BooleanField(default=False, help_text='Якщо True — учень може 1 раз перевірити здану роботу через ШІ', verbose_name='Дозволити учням самоперевірку ШІ'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='default_ai_grs',
            field=models.TextField(blank=True, default='', help_text='JSON-список code ГР, наприклад ["ГР 1","ГР 2"]', verbose_name='Активні ГР за замовчуванням (JSON)'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='default_ai_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_assignments', to='feed.aicriteriapreset', verbose_name='Шаблон оцінювання за замовчуванням'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_ai_accepted',
            field=models.BooleanField(default=False, verbose_name='Вчитель прийняв оцінку учня'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_ai_checked',
            field=models.BooleanField(default=False, verbose_name='Учень скористався самоперевіркою ШІ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_ai_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час самоперевірки учнем'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_ai_feedback',
            field=models.TextField(blank=True, default='', verbose_name='Чернова рецензія ШІ (від учня)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_ai_gr_results',
            field=models.TextField(blank=True, default='', verbose_name='Чернові оцінки ГР (від учня, JSON)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_ai_grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Чернова оцінка ШІ (від учня)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_ai_level',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Рівень чернової оцінки (від учня)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_ai_summary',
            field=models.TextField(blank=True, default='', verbose_name='Чернове резюме ШІ (від учня)'),
        ),
    ]
