# Generated by Django 6.1 on 2026-08-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_assignment_ai_defaults_student_selfcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Нотатки вчителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='feed.classgroup', verbose_name='Клас')),
            ],
            options={
                'verbose_name': 'Учень',
                'verbose_name_plural': 'Учні',
                'ordering': ['class_group__grade', 'class_group__letter', 'last_name', 'first_name'],
                'unique_together': {('last_name', 'first_name', 'class_group')},
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='feed.student', verbose_name='Учень'),
        ),
    ]
