# Generated by Django 6.1 on 2026-08-30 15:52

import django.db.models.deletion
import feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_student_submission_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=feed.models.submission_file_upload_path, verbose_name='Файл роботи')),
                ('original_name', models.CharField(blank=True, max_length=500, verbose_name='Оригінальна назва файлу')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Розмір файлу (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='feed.submission', verbose_name='Здача роботи')),
            ],
            options={
                'verbose_name': 'Файл зданої роботи',
                'verbose_name_plural': 'Файли зданих робіт',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
