# Generated by Django 6.1 on 2026-08-30 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_submissionfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='student_ai_accepted',
        ),
        migrations.AddField(
            model_name='submission',
            name='is_latest_attempt',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Остання (актуальна) спроба'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_resubmission',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Повторна здача (робота над помилками)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='previous_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_submissions', to='feed.submission', verbose_name='Попередня спроба'),
        ),
        migrations.AddField(
            model_name='submission',
            name='resubmission_attempt',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер спроби здачі'),
        ),
    ]
