# Generated by Django 6.1 on 2026-08-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_remove_submission_student_ai_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student_ai_accepted',
            field=models.BooleanField(default=False, verbose_name='Вчитель прийняв оцінку учня'),
        ),
    ]
