# Generated by Django 6.1 on 2026-08-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_submission_student_ai_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_ai_usage',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено, учням дозволено використовувати генеративний ШІ для виконання завдання', verbose_name='Дозволити використання ШІ учнями'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_generated_confidence',
            field=models.CharField(blank=True, choices=[('none', 'Ознак не виявлено'), ('low', 'Низька ймовірність'), ('medium', 'Середня ймовірність'), ('high', 'Висока ймовірність (явні ознаки ШІ)')], default='none', max_length=20, verbose_name='Ймовірність генерації ШІ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_generated_details',
            field=models.TextField(blank=True, default='', verbose_name='Деталі та ознаки використання ШІ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_generated_detected',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Виявлено ознаки використання ШІ'),
        ),
    ]
