# Generated by Django 6.1.1 on 2026-09-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_assignment_allow_ai_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='ai_detector_tolerance_percent',
            field=models.IntegerField(default=25, help_text='Поріг збігів або окремих слів (за замовчуванням 25%), нижче якого контент вважається самостійною роботою, а не ШІ', verbose_name='Допустимий відсоток запозичень/збігів без звинувачення в ШІ (%)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_generated_percent',
            field=models.IntegerField(blank=True, default=0, verbose_name='Розрахунковий відсоток генерації ШІ (%)'),
        ),
    ]
