# Generated by Django 6.1.1 on 2026-09-06 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_aisettings_ai_detector_tolerance_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер уроку')),
                ('start_time', models.TimeField(verbose_name='Початок уроку')),
                ('end_time', models.TimeField(verbose_name='Кінець уроку')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Дзвінок / урок',
                'verbose_name_plural': 'Розклад дзвінків',
                'ordering': ['lesson_number'],
            },
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='system_prompt',
            field=models.TextField(default='Ти — висококваліфікований шкільний педагог-експерт з оцінювання за критеріями Нової української школи (НУШ).\nТвоє завдання — об\'єктивно, доброзичливо та конструктивно проаналізувати виконане учнем завдання у порівнянні з умовою, вимогами вчителя та матеріалами уроку.\n\nКРИТЕРІЇ ТА ШКАЛА ОЦІНЮВАННЯ НУШ (1-12 БАЛІВ):\n1. Початковий рівень (1-3 бали):\n   - 1-3 бали: учень володіє лише фрагментарними знаннями, завдання виконано частково з грубими помилками або тема розкрита поверхнево.\n2. Середній рівень (4-6 балів):\n   - 4-6 балів: учень відтворює основний навчальний матеріал за зразком, присутні типові неточності чи розрахункові помилки, але базову структуру збережено.\n3. Достатній рівень (7-9 балів):\n   - 7-9 балів: учень самостійно застосовує знання у стандартних ситуаціях, правильно розв\'язано більшість завдань, робота містить незначні неточності чи погрішності в оформленні.\n4. Високий рівень (10-12 балів):\n   - 10-12 балів: глибоке засвоєння теми, бездоганне виконання, логічність, творчий підхід, обґрунтованість висновків та охайність.\n\nПРІОРИТЕТ ВИМОГ ВЧИТЕЛЯ ТА ОБСЯГ ЗАВДАННЯ (SCOPE OF WORK):\n- Текст у полі «ЗАВДАННЯ ДО ВИКОНАННЯ» від вчителя має АБСОЛЮТНИЙ ПРІОРИТЕТ над прикріпленими файлами чи матеріалами.\n- Прикріплений файл — це лише допоміжний роздатковий матеріал уроку. Якщо у файлі є кілька завдань (наприклад, 5 завдань чи вправ), але вчитель вказав виконати тільки одне конкретне (наприклад, завдання 3):\n  * Оцінюй ВИКЛЮЧНО вказане вчителем завдання.\n  * КАТЕГОРИЧНО ЗАБОРОНЕНО знижувати бал або писати зауваження про «невиконання решти завдань» — вони вважаються незаданими!\n  * Робота вважається виконаною у повному обсязі (100%), якщо якісно виконано саме задане вчителем завдання.\n\nТЕХНІЧНІ ВИМОГИ ТА ПРАВИЛА ДЛЯ ПОЛЯ "format_warning":\n- Поле "format_warning" призначене ВИКЛЮЧНО ДЛЯ ТЕХНІЧНИХ ДЕФЕКТІВ РОЗШИРЕННЯ ЧИ ТИПУ ФАЙЛУ (а НЕ для змісту роботи чи зображених об\'єктів!):\n  1. Якщо завдання з програмування (наприклад, Python, JS, C++ тощо), код повинен бути збережений у файлі з належним розширенням (наприклад, .py для Python, .html для веб, .cpp для C++).\n  2. Якщо файл здано БЕЗ РОЗШИРЕННЯ (навіть якщо всередині правильний код чи текст), або здано у технічно невідповідному типі файлу (наприклад, текстовий файл .txt замість .py коду чи замість .xlsx таблиці, або фото замість файлу коду):\n     * Обов\'язково зафіксуй технічне зауваження у полі "format_warning" (наприклад: "Файл здано без розширення (має бути .py для коду Python)").\n     * Обов\'язково додай це технічне зауваження до списку "weaknesses" та у "feedback_comment".\n     * ЗНИЗЬ рекомендовану оцінку на 1-2 бали за порушення технічних вимог до формату здачі.\n  3. СУВОРЕ ПРАВИЛО: Якщо файл має належний технічний формат (наприклад, валідне зображення .jpg/.png, документ .docx/.pdf тощо), але ЗМІСТ роботи не відповідає завданню (наприклад, на фото людина замість кота, есе не на ту тему, помилковий малюнок чи розв\'язок):\n     * Поле "format_warning" ОБОВ\'ЯЗКОВО МАЄ БУТИ null (або порожнім)!\n     * Усі зауваження щодо невідповідності змісту завдання фіксуй ВИКЛЮЧНО у "weaknesses" та "feedback_comment", а також знижуй оцінку або став рекомендований статус "Доопрацювати".\n\nОСОБЛИВИЙ СТАТУС "Доопрацювати":\nЯкщо робота не відповідає темі завдання (наприклад, завантажено стороннє фото чи чужий документ), здано порожній файл, або допущено критичні помилки, які вимагають переробки учнем, вкажи рекомендовану оцінку "Доопрацювати".\n\nФОРМАТ ВІДПОВІДІ (ТІЛЬКИ ВАЛІДНИЙ JSON БЕЗ ЗАЙВОГО ТЕКСТУ):\n{\n  "suggested_grade": "10",\n  "level": "Високий (10-12)",\n  "format_warning": null,\n  "summary": "Короткий загальний висновок щодо якості виконання.",\n  "strengths": ["Пункт 1: що зроблено відмінно", "Пункт 2: сильна сторона"],\n  "weaknesses": ["Пункт 1: на що звернути увагу чи виправлення помилок"],\n  "feedback_comment": "Повний розгорнутий доброзичливий відгук вчителя для учня з порадами.",\n  "status": "success"\n}\n', verbose_name='Системний промт (Критерії НУШ)'),
        ),
        migrations.AlterField(
            model_name='submissionactivitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Вхід в систему'), ('logout', 'Вихід із системи'), ('submission', 'Здача роботи'), ('grading', 'Оцінювання'), ('grade', 'Оцінювання'), ('grade_submission', 'Оцінювання здачі'), ('comment', 'Коментар'), ('delete', 'Видалення'), ('student_created', 'Додавання учня'), ('student_updated', 'Оновлення учня'), ('student_deleted', 'Видалення учня'), ('students_imported', 'Імпорт учнів')], max_length=20, verbose_name='Тип дії'),
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('missing_task', '⚠️ Немає завдання до уроку'), ('new_submission', '📥 Нова здана робота'), ('info', 'ℹ️ Інформація')], default='info', max_length=30, verbose_name='Тип сповіщення')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Посилання для дії')),
                ('action_label', models.CharField(blank=True, max_length=100, verbose_name='Підпис дії')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='feed.teacher', verbose_name='Вчитель')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentScheduleTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(blank=True, help_text='Дата, коли цей клас опрацьовує завдання на уроці', null=True, verbose_name='Цільова дата уроку')),
                ('target_day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Понеділок'), (2, 'Вівторок'), (3, 'Середа'), (4, 'Четвер'), (5, "П'ятниця"), (6, 'Субота')], null=True, verbose_name='День тижня за розкладом')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_targets', to='feed.assignment', verbose_name='Завдання')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_schedule_targets', to='feed.classgroup', verbose_name='Клас')),
                ('bell_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_targets', to='feed.bellschedule', verbose_name='Урок за розкладом')),
            ],
            options={
                'verbose_name': "Прив'язка завдання до розкладу",
                'verbose_name_plural': "Прив'язки завдань до розкладу",
                'unique_together': {('assignment', 'class_group')},
            },
        ),
        migrations.CreateModel(
            name='TeacherLessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Понеділок'), (2, 'Вівторок'), (3, 'Середа'), (4, 'Четвер'), (5, "П'ятниця"), (6, 'Субота')], default=1, verbose_name='День тижня')),
                ('bell_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_lessons', to='feed.bellschedule', verbose_name='Урок / дзвінок')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='feed.classgroup', verbose_name='Клас')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_schedules', to='feed.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='feed.teacher', verbose_name='Вчитель')),
            ],
            options={
                'verbose_name': 'Урок вчителя за розкладом',
                'verbose_name_plural': 'Розклад уроків вчителів',
                'ordering': ['day_of_week', 'bell_slot__lesson_number'],
                'unique_together': {('teacher', 'day_of_week', 'bell_slot')},
            },
        ),
    ]
