# Generated by Django 6.1.1 on 2026-09-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_bellschedule_alter_aisettings_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='conducted_lessons_last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час останньої зміни лічильника'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='conducted_lessons_manual_count',
            field=models.PositiveIntegerField(blank=True, help_text='Якщо вказано вчителем, використовується це число замість системного авто-розрахунку', null=True, verbose_name='Встановлена вручну кількість проведених уроків'),
        ),
        migrations.CreateModel(
            name='AssignmentRescheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(verbose_name='Початкова дата уроку')),
                ('new_date', models.DateField(verbose_name='Нова дата уроку')),
                ('reason_type', models.CharField(choices=[('air_raid', '🚨 Повітряна тривога'), ('illness', '🏥 Хвороба вчителя / лікарняний'), ('quarantine', '😷 Дистанційне навчання / карантин'), ('curriculum', '📚 Коригування навчальної програми'), ('holiday', '🎉 Свято / перенесення вихідного дня'), ('technical', '⚡ Технічні причини / аварія / відключення світла'), ('other', '✍️ Інша причина')], default='air_raid', max_length=40, verbose_name='Тип причини')),
                ('reason_comment', models.TextField(blank=True, verbose_name='Коментар / деталі перенесення')),
                ('rescheduled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата перенесення')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_logs', to='feed.assignment', verbose_name='Завдання')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_logs', to='feed.classgroup', verbose_name='Клас')),
                ('new_bell_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='feed.bellschedule', verbose_name='Новий урок')),
                ('original_bell_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='feed.bellschedule', verbose_name='Початковий урок')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_logs', to='feed.teacher', verbose_name='Вчитель')),
            ],
            options={
                'verbose_name': 'Запис перенесення уроку',
                'verbose_name_plural': 'Журнал перенесення уроків',
                'ordering': ['-rescheduled_at'],
            },
        ),
    ]
