# Generated by Django 6.1.1 on 2026-09-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_teacher_conducted_lessons_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['grade', 'letter', 'name'], 'verbose_name': 'Клас', 'verbose_name_plural': 'Класи'},
        ),
        migrations.AlterField(
            model_name='submission',
            name='ai_suggested_grade',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Попередня оцінка ШІ'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Оцінка'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student_ai_grade',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Чернова оцінка ШІ (від учня)'),
        ),
    ]
