# Generated by Django 6.1 on 2026-09-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0027_clean_raw_json_ai_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='group_authors',
            field=models.TextField(blank=True, default='', verbose_name='Співавтори / учасники групи'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_group_work',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Колективна робота'),
        ),
        migrations.AddField(
            model_name='submission',
            name='primary_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coauthor_submissions', to='feed.submission', verbose_name='Основна робота групи'),
        ),
    ]
