# Generated by Django 6.1 on 2026-09-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0028_submission_group_authors_submission_is_group_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentfile',
            name='is_task_source_for_ai',
            field=models.BooleanField(default=False, help_text='Позначка для ШІ, що саме у цьому файлі міститься умова/текст завдання', verbose_name='Файл з умовою для ШІ'),
        ),
    ]
