# Generated by Django 6.1 on 2026-09-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0031_alter_aisettings_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='no_submission_required',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено — на сайті вимикається кнопка здачі робіт для учнів (робота не передбачає завантаження матеріалів на сервер)', verbose_name='Не вимагає здачі робіт (завдання для опрацювання / усне)'),
        ),
    ]
