# Generated by Django 6.1 on 2026-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0032_assignment_no_submission_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aisettings',
            options={'verbose_name': 'Налаштування ШІ', 'verbose_name_plural': 'Налаштування ШІ'},
        ),
        migrations.AddField(
            model_name='aisettings',
            name='active_api_type',
            field=models.CharField(choices=[('primary', 'Основний API'), ('backup', 'Резервний API')], default='primary', help_text='Ручний вибір активного ключа: Основний або Резервний', max_length=20, verbose_name='Активний API ключ'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini (Офіційний API)'), ('openai', 'OpenAI (ChatGPT / GPT-4o)'), ('deepseek', 'DeepSeek (DeepSeek V3 / R1)'), ('groq', 'Groq Cloud (Llama / Mixtral)'), ('openrouter', 'OpenRouter (Універсальний доступ)'), ('custom', 'Власний OpenAI-сумісний (Ollama / Local AI / vLLM)')], default='gemini', help_text='Оберіть платформу ШІ для основного оцінювання', max_length=50, verbose_name='Основний провайдер ШІ'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='auto_failover_enabled',
            field=models.BooleanField(default=True, help_text='Автоматично використовувати резервний API у разі вичерпання лімітів (429 Rate Limit) чи збоїв', verbose_name='Автоматичне перемикання при збоях'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='backup_ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini (Офіційний API)'), ('openai', 'OpenAI (ChatGPT / GPT-4o)'), ('deepseek', 'DeepSeek (DeepSeek V3 / R1)'), ('groq', 'Groq Cloud (Llama / Mixtral)'), ('openrouter', 'OpenRouter (Універсальний доступ)'), ('custom', 'Власний OpenAI-сумісний (Ollama / Local AI / vLLM)')], default='gemini', help_text='Провайдер резервного API на випадок збоїв чи вичерпання лімітів', max_length=50, verbose_name='Резервний провайдер ШІ'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='backup_api_key',
            field=models.CharField(blank=True, default='', help_text='Резервний ключ для безперебійного оцінювання', max_length=255, verbose_name='Резервний API Key'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='backup_custom_api_url',
            field=models.CharField(blank=True, default='', help_text='Для резервного custom провайдера', max_length=255, verbose_name='Резервний Base URL'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='backup_model_name',
            field=models.CharField(blank=True, default='', help_text='Модель резервного API (якщо порожньо — використовується сумісна за замовчуванням)', max_length=100, verbose_name='Резервна модель'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='custom_api_url',
            field=models.CharField(blank=True, default='', help_text='Для custom провайдера або локальної Ollama, наприклад: http://localhost:11434/v1', max_length=255, verbose_name='Основний Base URL'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_failover_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час останнього перемикання'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_failover_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина останнього перемикання'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Отримайте ключ в Google AI Studio або кабінеті обраного ШІ', max_length=255, verbose_name='Основний API Key'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', help_text='Основна модель (Пріоритет #1)', max_length=100, verbose_name='Основна модель'),
        ),
    ]
