# Generated by Django 6.1 on 2026-09-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0033_alter_aisettings_options_aisettings_active_api_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='model_name',
            field=models.CharField(default='gemini-3.8-flash', help_text='Основна модель (Пріоритет #1)', max_length=100, verbose_name='Основна модель'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='saved_models_list',
            field=models.TextField(blank=True, default='[{"name": "gemini-3.8-flash", "priority": 1, "enabled": true}, {"name": "gemini-3.7-flash", "priority": 2, "enabled": true}, {"name": "gemini-3.1-flash-lite", "priority": 3, "enabled": true}, {"name": "gemini-3.1-pro-preview", "priority": 4, "enabled": true}]', verbose_name='Збережені моделі з пріоритетами'),
        ),
    ]
