# Generated by Django 6.1.1 on 2026-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0034_alter_aisettings_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ignore_plagiarism',
            field=models.BooleanField(db_index=True, default=False, help_text='Дозволяє вчителю вимкнути попередження про дублікати та плагіат, якщо учні виконували роботу спільно, але не зазначили співавторів при здачі.', verbose_name='Ігнорувати плагіат / спільна робота'),
        ),
    ]
