# Generated by Django 6.1 on 2026-09-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0041_assignment_ai_task_understanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_student_ai_understanding',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено — учні зможуть переглядати звіт «Як ШІ розуміє завдання» з поясненнями, адаптованими під їхній вік і клас', verbose_name='Дозволити учням бачити аналіз ШІ («Як ШІ розуміє завдання»)'),
        ),
    ]
