# Generated by Django 6.1 on 2026-09-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0043_sanitize_system_prompt_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='default_thinking_mode',
            field=models.BooleanField(default=False, help_text='ШІ детальніше розмірковує (Thinking budget) перед виставленням оцінок робіт учнів', verbose_name='Режим глибокого мислення за замовчуванням (Thinking mode)'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ai_thinking_mode',
            field=models.BooleanField(default=False, help_text='Увімкніть для складних завдань: ШІ виконуватиме поглиблений покроковий аналіз робіт перед виставленням оцінки', verbose_name='Режим глибокого мислення ШІ (Thinking mode)'),
        ),
        migrations.CreateModel(
            name='AIErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='evaluation', max_length=100, verbose_name='Дія ШІ')),
                ('provider', models.CharField(blank=True, default='', max_length=50, verbose_name='Провайдер')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Модель')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP Код')),
                ('error_type', models.CharField(blank=True, default='', max_length=150, verbose_name='Тип помилки')),
                ('error_message', models.TextField(verbose_name='Текст помилки')),
                ('prompt_preview', models.TextField(blank=True, default='', verbose_name='Фрагмент промта / контексту')),
                ('raw_response', models.TextField(blank=True, default='', verbose_name='Сира відповідь API')),
                ('failover_triggered', models.BooleanField(default=False, verbose_name='Спрацював Failover')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Час помилки')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_error_logs', to='feed.assignment', verbose_name='Завдання')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_error_logs', to='feed.submission', verbose_name='Робота учня')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_error_logs', to='feed.teacher', verbose_name='Вчитель')),
            ],
            options={
                'verbose_name': 'Помилка ШІ',
                'verbose_name_plural': 'Журнал помилок ШІ',
                'ordering': ['-created_at'],
            },
        ),
    ]
