# Generated by Django 6.1.1 on 2026-09-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0045_alter_aisettings_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='Модель')),
                ('provider', models.CharField(db_index=True, default='gemini', max_length=50, verbose_name='Провайдер')),
                ('action', models.CharField(default='evaluation', max_length=100, verbose_name='Дія')),
                ('status_code', models.IntegerField(default=200, verbose_name='HTTP Статус')),
                ('is_success', models.BooleanField(default=True, verbose_name='Успішний запит')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='Вхідні токени (Prompt)')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='Вихідні токени (Candidates)')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Всього токенів')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='Тривалість (мс)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Час запиту')),
            ],
            options={
                'verbose_name': 'Запит ШІ / Токени',
                'verbose_name_plural': 'Журнал запитів та токенів ШІ',
                'ordering': ['-created_at'],
            },
        ),
    ]
