# Generated by Django 6.1 on 2026-10-03 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0047_aijob_studentaicheckreservation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'understanding'), ('status__in', ['queued', 'running'])), fields=('assignment',), name='one_active_ai_understanding_per_assignment'),
        ),
    ]
