# Generated by Django 6.1 on 2026-10-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0050_submission_ai_percent_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='usage_reported',
            field=models.BooleanField(default=False, verbose_name='API повернув кількість токенів'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='provider_connections',
            field=models.JSONField(blank=True, default=list, verbose_name='Підключення до постачальників ШІ'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='unified_model_queue',
            field=models.BooleanField(default=False, editable=False, verbose_name='Налаштування перенесено до єдиної черги'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_completion_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вихідні токени перевірки'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_prompt_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вхідні токени перевірки'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_provider_used',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Постачальник перевірки ШІ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_request_model',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Модель у відповіді API'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_total_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Всього токенів перевірки'),
        ),
    ]
