# Generated by Django 6.1 on 2026-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0053_aijob_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini (Офіційний API)'), ('openai', 'OpenAI (ChatGPT / GPT-4o)'), ('deepseek', 'DeepSeek (DeepSeek V3 / R1)'), ('groq', 'Groq Cloud (Llama / Mixtral)'), ('openrouter', 'OpenRouter (Універсальний доступ)'), ('cloudflare', 'Cloudflare Workers AI'), ('custom', 'Власний OpenAI-сумісний (Ollama / Local AI / vLLM)')], default='gemini', help_text='Оберіть платформу ШІ для основного оцінювання', max_length=50, verbose_name='Основний провайдер ШІ'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='backup_ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini (Офіційний API)'), ('openai', 'OpenAI (ChatGPT / GPT-4o)'), ('deepseek', 'DeepSeek (DeepSeek V3 / R1)'), ('groq', 'Groq Cloud (Llama / Mixtral)'), ('openrouter', 'OpenRouter (Універсальний доступ)'), ('cloudflare', 'Cloudflare Workers AI'), ('custom', 'Власний OpenAI-сумісний (Ollama / Local AI / vLLM)')], default='gemini', help_text='Провайдер резервного API на випадок збоїв чи вичерпання лімітів', max_length=50, verbose_name='Резервний провайдер ШІ'),
        ),
        migrations.AlterField(
            model_name='submissionactivitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Вхід в систему'), ('logout', 'Вихід із системи'), ('submission', 'Здача роботи'), ('grading', 'Оцінювання'), ('grade', 'Оцінювання'), ('grade_submission', 'Оцінювання здачі'), ('comment', 'Коментар'), ('delete', 'Видалення'), ('student_created', 'Додавання учня'), ('student_updated', 'Оновлення учня'), ('student_deleted', 'Видалення учня'), ('students_imported', 'Імпорт учнів'), ('students_merged', "Об'єднання учнів"), ('group_authors', 'Склад групи')], max_length=20, verbose_name='Тип дії'),
        ),
    ]
