# Generated by Django 6.1 on 2026-10-08 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0054_alter_aisettings_ai_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aierrorlog',
            name='connection_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID підключення'),
        ),
        migrations.AddField(
            model_name='aierrorlog',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Зчитано для аналізу / звіту'),
        ),
        migrations.AddField(
            model_name='aierrorlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час зчитування'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='connection_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID підключення'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_connection_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID підключення ШІ'),
        ),
        migrations.CreateModel(
            name='AIErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Час створення')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Кількість проаналізованих помилок')),
                ('unread_count_before', models.IntegerField(default=0, verbose_name='Було незчитаних')),
                ('verdict', models.CharField(default='external_issue', max_length=50, verbose_name='Вердикт')),
                ('verdict_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Короткий висновок')),
                ('report_text', models.TextField(verbose_name='Текст звіту (Markdown)')),
                ('model_used', models.CharField(blank=True, default='', max_length=100, verbose_name='Модель, що сформувала звіт')),
                ('raw_summary', models.TextField(blank=True, default='', verbose_name='Вхідні дані помилок (JSON)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_error_reports', to='feed.teacher', verbose_name='Вчитель / Адміністратор')),
            ],
            options={
                'verbose_name': 'Звіт аналізу помилок ШІ',
                'verbose_name_plural': 'Звіти аналізу помилок ШІ',
                'ordering': ['-created_at'],
            },
        ),
    ]
