# Generated by Django 6.1 on 2026-10-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0055_aierrorlog_connection_id_aierrorlog_is_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Локальний журнал оцінок', max_length=150, verbose_name='Назва / Призначення')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='API ключ / Токен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('can_export_grades', models.BooleanField(default=True, verbose_name='Дозвіл на вивантаження оцінок')),
                ('can_import_roster', models.BooleanField(default=True, verbose_name='Дозвіл на синхронізацію учнів та класів')),
                ('local_journal_url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL локального журналу (опціонально)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Останнє використання')),
                ('requests_count', models.PositiveIntegerField(default=0, verbose_name='Кількість запитів')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_api_keys', to='feed.teacher', verbose_name='Власник (вчитель)')),
            ],
            options={
                'verbose_name': 'API ключ журналу',
                'verbose_name_plural': 'API ключі журналу',
                'ordering': ['-created_at'],
            },
        ),
    ]
