# Generated by Django 6.1.2 on 2026-10-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0056_journalapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterReplica',
            fields=[
                ('ref', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RosterState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='integration_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='integration_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
